-- Blueprint HR (main) - i18n translation cache for Operations + HR mail
-- Adds original_language + translations jsonb to tables that hold
-- user-facing free-text content but were missing the i18n metadata.
--
-- Pairs with the lib/i18n/get-localized.ts + components/shared/
-- LocalizedText.tsx render layer added in this branch: every translatable
-- field is shown in the viewer's locale automatically, with translations
-- lazily generated on first view and cached on the row.
--
-- Additive only (ADD COLUMN IF NOT EXISTS). Safe to re-run.

-- =====================================================================
-- Operations module — daily reports + extracted items + recurring themes
-- =====================================================================

ALTER TABLE op_reports
  ADD COLUMN IF NOT EXISTS original_language TEXT
    CHECK (original_language IN ('he','en','tl','unknown'));

ALTER TABLE op_report_items
  ADD COLUMN IF NOT EXISTS original_language TEXT
    CHECK (original_language IN ('he','en','tl','unknown'));
ALTER TABLE op_report_items
  ADD COLUMN IF NOT EXISTS translations JSONB DEFAULT '{}'::jsonb;

-- Recurring themes are generated by the cron in canonical English from
-- now on; render-side LocalizedText translates per viewer and caches.
ALTER TABLE op_recurring_themes
  ADD COLUMN IF NOT EXISTS translations JSONB DEFAULT '{}'::jsonb;

-- =====================================================================
-- HR Mail — inbound emails classified into HR workflows
-- =====================================================================

ALTER TABLE hr_emails
  ADD COLUMN IF NOT EXISTS original_language TEXT
    CHECK (original_language IN ('he','en','tl','unknown'));
ALTER TABLE hr_emails
  ADD COLUMN IF NOT EXISTS translations JSONB DEFAULT '{}'::jsonb;

-- =====================================================================
-- Indexes for analytics ("% of reports ingested in Hebrew") and native-skip
-- =====================================================================

CREATE INDEX IF NOT EXISTS idx_op_reports_orig_lang ON op_reports(original_language);
CREATE INDEX IF NOT EXISTS idx_op_report_items_orig_lang ON op_report_items(original_language);
CREATE INDEX IF NOT EXISTS idx_hr_emails_orig_lang ON hr_emails(original_language);
